const es = {
  translation: {
    "enter": "Entrar",
    "home": {
      "welcome": {
        "who": "¿Quiénes somos?",
        "cgv": "Términos y Condiciones",
        "contact": "Contactar",
      },
      "who": {
        "texte1": "OcéNat Créations es una pequeña empresa artesanal, sobre todo francesa y ecológicamente responsable.",
      "liste1": "para trabajar solo con fibras naturales (animales o plantas),",
      "liste2": "para participar en el reciclaje de ropa, la segunda industria más contaminante del mundo, y mucha ropa apenas se usa antes de tirarse,",
      "liste3": "y para mantener la idea, también hemos desarrollado un rango de cero desperdicio que lo ayudará a eliminar el plástico de su vida diaria (bolsa a granel, charlotte plano o envolturas de abejas ...) y hacer ahorro a largo plazo.",
      "texte2": "Después de haber trabajado como observador científico a bordo, me di cuenta rápidamente del impacto del plástico en los océanos. ¿Pero qué es el plástico? Un poco de todo, de hecho, se encuentra en fibras sintéticas como el vellón polar en forma de micropartículas, y son estas las que forman continentes en ciertas áreas de los océanos y destruyen una gran parte de la fauna porque son invisibles pero se absorben.",
      "texte3": "Entonces decidimos:",
      "texte4": "Nuestros proveedores son elegidos con el mayor cuidado para cumplir con nuestros muchos requisitos. Intentamos trabajar lo más posible con lanas / hilos / telas con la etiqueta GOTS, o Okéo-tex, luego siempre favorecemos las producciones para limitar las emisiones de carbono",
      "texte5": "este sitio se los presenta en su tienda, en 3 categorías. También encontrará algunos artículos sobre ecología y la industria textil, así como sobre fibras y tutoriales.",
      "texte6": "no dude en suscribirse, recibirá nuestro boletín (aproximadamente 4 por año) y podrá comentar sus artículos favoritos",
      "texte7": "Que tengas una buena visita",
      "title": "¿Quiénes somos?"
      },
      "condition": {
        "lien1": "Nuestras condiciones generales de venta se han elaborado a partir de un modelo gratuito que se puede descargar del sitio: ",
        "soustitre1": 'Artículo 1: Asunto',
        "soustitre10": 'Artículo 10: Pago',
        "soustitre11": 'Artículo 11: Garantías',
        "soustitre12": 'Artículo 12: Quejas y mediación',
        "soustitre13": 'Artículo 13: rescisión del contrato',
        "soustitre14": 'Artículo 14: Derechos de propiedad intelectual',
        "soustitre15": 'Artículo 15: Fuerza mayor',
        "soustitre16": 'Artículo 16: Nulidad y modificación del contrato',
        "soustitre17": 'Artículo 17: Protección de datos personales',
        "soustitre18": 'Artículo 18: Ley y cláusulas aplicables',
        "soustitre19": 'Artículo 19: Información al consumidor',
        "soustitre2": 'Artículo 2: Disposiciones generales',
        "soustitre3": 'Artículo 3: Precio',
        "soustitre4": 'Artículo 4: Celebración del contrato en línea',
        "soustitre5": 'Artículo 5: Productos y servicios',
        "soustitre6": 'Artículo 6: Cumplimiento',
        "soustitre7": 'Artículo 7: cláusula de reserva de propiedad',
        "soustitre8": 'Artículo 8: Condiciones de entrega',
        "soustitre9": 'Artículo 9: Disponibilidad y presentación',
        "strong1": " Aceptación de estas Condiciones Generales de Venta",
        "texte1": 'Entre la microempresa OcéNat Créations, ',
        "texte10": "En adelante,'' el Comprador '', o'' el Cliente ''Por otro lado, se ha establecido y acordado lo siguiente:",
        "texte11": 'El Vendedor es el editor de Productos OcéNat Créations destinados a los consumidores, comercializados a través de sus sitios web (http://siteweb.com). La lista y descripción de los bienes y servicios ofrecidos por la Compañía pueden ser visto en los sitios antes mencionados. ',
        "texte12": 'Estas Condiciones Generales de Venta determinan los derechos y obligaciones de las partes en el marco de la venta online de Productos o Servicios ofrecidos por el Vendedor. ',
        "texte13": 'Estas Condiciones Generales de Venta (TCG) rigen la venta de Productos o Servicios, realizada a través de los sitios web de la Compañía, y son una parte integral del Contrato entre el Comprador y el Vendedor. Son totalmente exigibles contra el Comprador que los aceptó antes de realizar un pedido. ',
        "texte14": 'El Vendedor se reserva el derecho de modificar las presentes condiciones, en cualquier momento mediante la publicación de una nueva versión en su sitio web. Los TCG entonces aplicables son los vigentes en la fecha de pago (o del primer pago en caso de pagos múltiples) del pedido. Estos Términos y Condiciones están disponibles en el sitio web de la Compañía en la siguiente dirección: ',
        "texte15": "http://ocenatcreations.com/homes/condition",
        "texte16": 'La Compañía también se asegura de que su aceptación sea clara y sin reservas al configurar una casilla de verificación y un clic de validación. El Cliente declara haber leído todos estos Términos y condiciones generales de venta, y en su caso, las Condiciones Especiales de Venta relacionadas con un producto o servicio, y aceptarlas sin restricción ni reserva. ',
        "texte17": 'El Cliente reconoce que ha recibido el asesoramiento y la información necesarios para garantizar que la oferta satisface sus necesidades. ',
        "texte18": 'El Cliente declara poder contratar legalmente bajo la ley francesa o representar a la persona física o jurídica por quien está comprometido. Salvo prueba en contrario, la información registrada por la Compañía constituye prueba de todas las transacciones . ',
        "texte19": 'Los precios de los productos vendidos a través de los sitios de Internet se indican en euros sin impuestos y se determinan con precisión en las páginas de descripción del producto. También se indican en euros, incluidos todos los impuestos (IVA + cualquier otro impuesto) en la página de pedidos de productos y excluyendo los costos de envío específicos. Para todos los productos enviados fuera de la Unión Europea y / o DOM-TOM, el precio se calcula automáticamente sin incluir los impuestos en la factura. Derechos de aduana u otros impuestos o aranceles locales En ciertos casos, es probable que se deban pagar impuestos de importación o estatales. Estos derechos y sumas no son responsabilidad del Vendedor. Serán responsabilidad del comprador y son su responsabilidad (declaraciones, pago a las autoridades competentes, etc.) Por lo tanto, el Vendedor invita al comprador a consultar estos aspectos con las autoridades locales correspondientes.La Compañía se reserva el derecho de modificar sus precios en cualquier momento para el ven. Los costos de telecomunicaciones necesarios para acceder a los sitios web de la Compañía son responsabilidad del Cliente. En su caso, también los gastos de envío. ',
        "texte2": '16rue des Tilleuls, ',
        "texte20": 'De acuerdo con lo dispuesto en el artículo 1127-1 del Código Civil, el Cliente debe seguir una serie de pasos para concluir el contrato electrónicamente con el fin de poder realizar su pedido :; Información sobre las características esenciales del Producto; - Elección del Producto, en su caso, de sus opciones - Indicación de los datos de contacto esenciales del Cliente (identificación, correo electrónico, dirección, etc.); - ',
        "texte21": "Verificación de los elementos del pedido (trámite de doble clic) y, en su caso, corrección de errores. Antes de proceder a su confirmación, el Comprador tiene la posibilidad de verificar los detalles de su pedido, su precio y para corregir cualquier error, o cancelar su pedido. La confirmación del pedido constituirá el presente contrato. - Seguidamente, siga las instrucciones de pago, pago de los productos, luego entrega del pedido. El Cliente recibirá la confirmación por correo electrónico del pago del pedido, así como acuse de recibo del mismo que lo confirma.Recibirá una copia en formato pdf de estas condiciones generales de venta.El cliente tendrá durante su proceso de pedido la posibilidad de identificar los errores cometidos. en la introducción de datos y su corrección. El idioma propuesto para la celebración del contrato es el francés. Los términos de la oferta y las condiciones generales de venta son enviado por correo electrónico al comprador al realizar el pedido y archivado en el sitio web del vendedor. En su caso, las reglas profesionales y comerciales a las que el autor de la oferta pretende acatar se pueden consultar en la sección de ''reglas adicionales'' de estos TCG, disponible en el sitio web del Vendedor en la siguiente dirección. El archivo de las comunicaciones, el pedido, los detalles del pedido, así como las facturas se realiza en un soporte fidedigno y duradero con el fin de constituir una copia fiel y duradera de acuerdo con lo dispuesto en el artículo 1360 del código civil. Esta información se puede presentar como prueba del contrato. Para los productos entregados, la entrega se realizará a la dirección indicada por el Cliente. A los efectos de la finalización satisfactoria del pedido, el Cliente se compromete a proporcionar sus verdaderos elementos de identificación. El Vendedor se reserva el derecho de rechazar el pedido, por ejemplo, por cualquier solicitud anormal, realizada de mala fe o por cualquier motivo legítimo. ",
        "texte22": 'Las características esenciales de los bienes, servicios y sus respectivos precios se ponen a disposición del comprador en los sitios web de la empresa, así como, en su caso, la forma de uso del producto. De acuerdo con el artículo L112-1 del Código de Consumo, se informa al consumidor, mediante marcado, etiquetado, exhibición o cualquier otro proceso adecuado, de los precios y las condiciones especiales de venta y de las ejecución de servicios antes de cualquier conclusión del contrato de venta. En todos los casos, el monto total adeudado por el Comprador se indica en la página de confirmación del pedido. El precio de venta del producto es el vigente indicado el día del pedido, éste sin incluir los gastos de envío facturados además. Estos posibles costes se indican al Comprador durante el proceso de venta, y en todo caso en el momento de la confirmación del pedido. El Vendedor se reserva el derecho a modificar sus precios en cualquier momento, garantizando la aplicación del precio indicado en el momento del pedido. Cuando los productos o servicios no se ejecutan de inmediato, se proporciona información clara en la página de presentación del producto en cuanto a las fechas de entrega de los productos o servicios. El cliente certifica haber recibido un detalle de los gastos de envío así como las condiciones de pago, entrega y ejecución del contrato, así como información detallada relativa a la identidad del vendedor, sus datos de contacto postales, telefónicos y electrónicos, y a sus actividades en el contexto de esta venta. El Vendedor se compromete a cumplir con el pedido del Cliente dentro del límite de las existencias de Productos disponibles únicamente. De lo contrario, el Vendedor informa al Cliente; si se ha realizado el pedido, y en ausencia de acuerdo con el Cliente sobre una nueva fecha de entrega, el Vendedor reembolsa al cliente. La información contractual se presenta detalladamente y en francés. Les parties conviennent que les illustrations ou photos des produits offerts à la vente n’ont pas de valeur contractuelle. La durée de validité de l’offre des Produits ainsi que leurs prix est précisée sur les sites Internet de la Société, ainsi que la durée minimale des contrats proposés lorsque ceux-ci portent sur une fourniture continue ou périodique de produits ou services. Sauf conditions particulières, les droits concédés au titre des présentes le sont uniquement à la personne physique signataire de la commande (ou la personne titulaire de l’adresse email communiqué). ',
        "texte23": 'De acuerdo con el artículo L.411-1 del Código del Consumidor, los productos y servicios ofrecidos a la venta a través de estos GTCS cumplen con los requisitos vigentes relacionados con la seguridad y salud de las personas, para equidad en las transacciones comerciales y protección del consumidor. Independientemente de cualquier garantía comercial, el vendedor sigue siendo responsable de cualquier falta de conformidad y vicios ocultos en el producto. De acuerdo con el artículo L.217-4, el vendedor entrega un bien conforme del contrato y responde a cualquier falta de conformidad existente en el momento de la entrega. También responde a cualquier falta de conformidad derivada del embalaje, instrucciones de montaje o instalación cuando le haya sido a cargo del contrato o ha sido realizado bajo su responsabilidad De acuerdo con las disposiciones legales sobre conformidad y vicios ocultos (art. 1641 civ. c.), el Vendedor reembolsa o cambia los productos defectuosos o productos que no correspondan al c. orden. El reembolso se puede solicitar de la siguiente manera: Si al recibirlo se encuentra un defecto, se debe enviar un correo electrónico dentro de las 48 horas para informar el problema con fotos, el producto debe ser devuelto (los costos de envío correrán a cargo del cliente salvo acuerdo previo por correo electrónico) en un plazo máximo de 10 días para proceder a un cambio o devolución (salvo problema de tallas y que se deba a un error del cliente en el formulario de pedido). ',
        "texte24": 'Los productos siguen siendo propiedad de la Compañía hasta el pago total del precio. ',
        "texte25": "Los productos se entregan en la dirección de entrega que se indicó al realizar el pedido y dentro de los tiempos indicados. Estos tiempos no tienen en cuenta el tiempo que se tarda en preparar el pedido. Cuando el Cliente pide varios productos a la vez. Estos pueden tener diferentes tiempos de entrega distribuidos de la siguiente manera: los productos de cero desperdicio y reciclaje se empaquetan y envían dentro de los 8 días posteriores a la confirmación del pedido, los modelos de recolección personalizados se empaquetan y envían entre 4 y 6 semanas. Todos los productos son enviados por UPS o Mondial Relay a su domicilio o punto de retransmisión según los términos definidos por el cliente al realizar el pedido. En caso de retraso en el envío, el cliente será contactado por correo electrónico o por teléfono en orden. para darle la posibilidad de cancelar o confirmar su pedido, la cancelación da derecho a la devolución total de las sumas ya pagadas. En caso de retraso en la entrega, el Cliente tiene derecho a posibilidad de rescindir el contrato en los términos y condiciones definidos en el artículo L 138-2 del Código del Consumidor. El Vendedor reembolsa el producto y los costos de ''salida'' en las condiciones del artículo L 138-3 del Código del Consumidor. El Vendedor proporciona un punto de contacto telefónico (costo de una llamada local desde un teléfono fijo) indicado en el correo electrónico de confirmación del pedido para dar seguimiento al pedido. El Vendedor recuerda que cuando el Cliente toma posesión física de los productos, se le transfiere el riesgo de pérdida o daño de los productos. Es responsabilidad del Cliente notificar al transportista de cualquier reserva sobre el producto entregado. ",
        "texte26": 'En el caso de que un artículo no esté disponible por un período superior a 10 días hábiles, se le notificará inmediatamente de los plazos de entrega previsibles y el pedido de este artículo puede cancelarse si lo solicita. El Cliente puede entonces solicitar una nota de crédito. por el importe del artículo o su devolución total y cancelación del pedido. ',
        "texte27": 'El pago vence inmediatamente después de realizar el pedido, incluidos los productos pedidos por adelantado. El cliente puede pagar con tarjeta de pago o cheque bancario. Las tarjetas emitidas por bancos domiciliados fuera de Francia deben ser tarjetas bancarias internacional (Mastercard o Visa). El pago seguro en línea con tarjeta de crédito lo realiza nuestro proveedor de servicios de pago. La información transmitida está encriptada de acuerdo con las reglas de la técnica y no se puede leer durante el transporte en la red ',
        "texte27bis": 'Una vez que el Cliente ha iniciado el pago, la transacción se carga inmediatamente después de la verificación de la información. De acuerdo con lo establecido en el Código Monetario y Financiero, el compromiso de pago otorgado con tarjeta es irrevocable. Al comunicar su información bancaria durante el venta, el Cliente autoriza al Vendedor a debitar su tarjeta por el importe correspondiente al precio indicado El Cliente confirma que es efectivamente el titular legal de la tarjeta a debitar y que está legalmente autorizado a utilizarla. error, o imposibilidad de cargar la tarjeta, la Venta se resuelve inmediatamente de forma automática y el pedido cancelado Artículo 11: Plazo de desistimiento De acuerdo con lo dispuesto en el Artículo L 221-5 del Código del Consumidor, El Comprador tiene derecho a desistir sin dar ningún motivo, dentro de los catorce (14) días a partir de la fecha de recepción de su pedido. El derecho de desistimiento puede ejercerse poniéndose en contacto con la Compañía de la siguiente manera: por simple correo electrónico. Si el derecho de desistimiento se ejerce dentro del plazo antes mencionado, se reembolsará el precio del producto o productos adquiridos y los gastos de envío, siendo los gastos de devolución a cargo del Cliente. Las devoluciones de productos deben realizarse en su estado original y completas (embalaje, accesorios, instrucciones, etc.); si es posible, deben ir acompañadas de una copia del comprobante de compra. De acuerdo con las disposiciones legales, encontrará a continuación el formulario de desistimiento estándar que se nos enviará a la siguiente dirección: ',
        "texte27ter": 'Procedimiento de reembolso: el reembolso se realizará mediante transferencia bancaria en un plazo de 3 días (excluyendo el plazo bancario) tras la recepción del paquete de devolución. ',
        "texte28": 'De conformidad con la ley, el Vendedor asume las siguientes garantías: de conformidad y relativas a defectos ocultos de los productos. El Vendedor reembolsa al comprador o cambia los productos aparentemente defectuosos o no correspondientes al pedido realizado. La solicitud de devolución debe llevarse a cabo de la siguiente manera: _________ (detalle el procedimiento) El Vendedor recuerda que el consumidor: - tiene un plazo de 2 años desde la entrega del bien para actuar con el Vendedor - que puede elegir entre la reposición y reparación de la mercancía sujeta a las condiciones previstas por las disposiciones anteriores - aparentemente defectuosa o no correspondiente - que se exime de acreditar la existencia de la falta de conformidad de la mercancía durante los seis meses siguientes a la emisión de la - que, a excepción de los bienes de segunda mano, este plazo se ampliará a 24 meses a partir del 18 de marzo de 2016 - que el consumidor también podrá hacer valer la garantía contra vicios ocultos del cosa vendida en el sentido del artículo 1641 del código civil y, en este caso, podrá optar entre la resolución de la compraventa o una rebaja del precio de venta (disposiciones de los artículos 1644 del código civil). Garantías adicionales: _____ (describa sus garantías adicionales) (esta, todavía no sé qué ponerme, tengo que averiguarlo bien, no he reemplazado cosas después de 2 años ^^) ',
        "texte29": 'En su caso, el Comprador podrá presentar cualquier reclamación poniéndose en contacto con la empresa utilizando las siguientes coordenadas _____ (indicar los datos de contacto y el procedimiento). De conformidad con lo dispuesto en los artículos L. 611-1 a L. 616-3 del Código del Consumidor, se informa al consumidor que podrá recurrir a un mediador del consumidor en las condiciones previstas en el Título I del Libro VI del Código del Consumidor. En caso de fallo de la reclamación solicitar al Servicio al cliente del Vendedor, o en ausencia de una respuesta dentro de los dos meses, el consumidor puede presentar la disputa a un mediador Para ver con mi seguro profesional que intentará con toda independencia unir a las partes para obtener una solución amistosa . ',
        "texte3": "16360 Baignes Ste Radegonde",
        "texte30": 'El pedido podrá ser resuelto por el comprador mediante carta certificada con acuse de recibo en los siguientes casos: - entrega de un producto que no cumpla con las características del pedido; - entrega superando el plazo fijado en el momento de el pedido o, en su defecto, dentro de los treinta días siguientes al pago; - aumento injustificado de precio o modificación del producto. En estos casos, el comprador podrá exigir el reembolso del depósito pagado más los intereses calculados sobre la Tasa legal a partir de la fecha de recepción del depósito. ',
        "texte31": 'Las marcas comerciales, los nombres de dominio, los productos, el software, las imágenes, los videos, los textos o, en general, cualquier información sujeta a derechos de propiedad intelectual son y siguen siendo propiedad exclusiva del vendedor. No se realiza ninguna transferencia de derechos de propiedad intelectual a través de estos TCG. Cualquier reproducción, modificación o uso total o parcial de estos bienes por cualquier motivo está estrictamente prohibido. ',
        "texte32": "La ejecución de las obligaciones del vendedor al final del presente contrato se suspende en caso de que se produzca un evento fortuito o de fuerza mayor que impida la ejecución. El vendedor notificará al cliente de la ocurrencia de tal evento tan pronto como como sea posible. ",
        "texte33": "Si una de las estipulaciones de este contrato fuera cancelada, esta nulidad no implicaría la nulidad de las demás estipulaciones que seguirán vigentes entre las partes. Cualquier modificación contractual solo es válida después de un acuerdo escrito firmado por las partes. partes. ",
        "texte34": 'De conformidad con el Reglamento 2016/679 del 27 de abril de 2016 sobre la protección de las personas con respecto al procesamiento de datos personales y la libre circulación de dichos datos, el Vendedor establece un procesamiento de datos personales cuyo objeto es la venta y entrega de productos y servicios definidos en este contrato. Se informa al Comprador de lo siguiente: - la identidad y los datos de contacto del responsable del tratamiento y, en su caso, del representante del responsable del tratamiento : el Vendedor, como se indica en la parte superior de estos TCG; - los datos de contacto del delegado de protección de datos: ???? - la base legal del procesamiento: ejecución contractual - los destinatarios o categorías de destinatarios de los datos de carácter personal, si existen: el controlador, sus departamentos encargados de marketing, los departamentos encargados de seguridad informática, el departamento encargado de ventas, entrega y el pedido, los subcontratistas involucrados en las operaciones de entrega y venta, así como cualquier autoridad legalmente autorizada para acceder a los datos personales en cuestión - no está prevista ninguna transferencia fuera de la UE - el período de conservación de los datos: tiempo de la prescripción comercial: el interesado tiene derecho a solicitar al responsable del tratamiento el acceso a los datos personales, la rectificación o supresión de estos, o una limitación del tratamiento en relación con el interesado, o derecho a oponerse al tratamiento y derecho a la portabilidad de los datos - El interesado tiene derecho a presentar una reclamación ante una autoridad de control - la información solicitada al realizar el pedido es necesaria para establecer el factura (obligación legal) y entrega de la mercancía solicitada, de lo contrario no se podrá realizar el pedido. No se implementan decisiones automatizadas o perfiles a través del proceso de pedido. ',
        "texte35": 'Todas las cláusulas que figuran en estas condiciones generales de venta, así como todas las operaciones de compraventa a las que se refieren, estarán sometidas a la ley francesa. La nulidad de una cláusula contractual no implica la nulidad de estas condiciones generales de venta. ',
        "texte36": 'A efectos de información al consumidor, a continuación se reproducen las disposiciones del Código Civil y del Código del Consumidor: Artículo 1641 del Código Civil: El vendedor está obligado por la garantía debido a los defectos ocultos del artículo vendido que lo hacen inadecuados para el uso al que está destinado, o que reducen tanto este uso que el comprador no los hubiera adquirido, o hubiera dado solo un precio inferior, si los hubiera conocido. Artículo 1648 del Código Civil: La acción resultante de defectos latentes debe ser interpuesta por el comprador dentro de los dos años siguientes al descubrimiento del defecto. En el caso previsto en el artículo 1642-1, la acción deberá interponerse, bajo pena de ejecución hipotecaria, dentro del plazo de un año desde la fecha en que el vendedor pueda ser liberado de defectos aparentes o falta de conformidad. Artículo L. 217-4 del Código del Consumidor: El vendedor entrega la mercancía de conformidad con el contrato y es responsable de cualquier falta de conformidad existente en el momento de la entrega. También responde a cualquier falta de conformidad resultante del embalaje, instrucciones de montaje o instalación cuando le haya sido a cargo del contrato o se haya realizado bajo su responsabilidad. Artículo L. 217-5 del Código del Consumidor: El bien se ajusta al contrato: 1 ° Si es apto para el uso que normalmente se espera de un bien similar y, en su caso: - si corresponde a la descripción dada por el vendedor y tiene las cualidades que este presentado al comprador como muestra o modelo; - si tiene las cualidades que un comprador puede esperar legítimamente dadas las declaraciones públicas hechas por el vendedor, el productor o su representante, en particular en publicidad o etiquetado; 2 ° O si tiene las características definidas de mutuo acuerdo por las partes o es apto para cualquier uso especial buscado por el comprador, puesto en conocimiento del vendedor y que éste ha aceptado. Artículo L. 217-12 del Código del Consumidor: La acción resultante de la falta de conformidad prescribe dos años después de la entrega de la mercancía. Artículo L. 217-16 del Código del Consumidor: Cuando el comprador solicite al vendedor, durante el curso de la garantía comercial que le fue otorgada durante la adquisición o reparación de bienes muebles, condición cubierta por la garantía, cualquier tiempo de inactividad de al menos siete días se agrega al período de garantía restante. Este plazo se extiende desde la solicitud de intervención del comprador o la disposición para la reparación del inmueble en cuestión, si esta disposición es posterior a la solicitud de intervención. ',
        "texte4": 'inscrito en el Registro de la Cámara de Comercio y Artesanía de Charente, ',
        "texte5": "bajo el número SIRET 0000000000, ",
        "texte6": 'representada por la Sra. Bernard Sonia como gerente, debidamente autorizada a los efectos del presente. ',
        "texte7": 'Se puede contactar a la empresa por correo electrónico haciendo clic en el formulario de contacto accesible a través de la página de inicio del sitio. ',
        "texte8": "En adelante, el' Vendedor 'o la' Compañía '. ",
        "texte9": 'Por un lado, Y la persona física o jurídica que adquiere los productos o servicios de la empresa, ',
        "title": "CONDICIONES GENERALES DE VENTA "
      },
      "contact": {
        "title": "Contactar",
        "texte1": "Contactar con nosotros: ",
        "texte2": "Teléfono: ",
      },
      "description": "OcéNat Créations .... Por el océano y la naturaleza ... Es a través de nuestra producción y consumo que podemos trabajar. Aquí encontrará cero desperdicio, tejido / crochet en materiales nobles y naturales y si es posible francés. Buen descubrimiento",
    },
    "shop": {
      "menu": {
        "zero": "Cero desperdicio",
        "accessory": "Accesorios",
        "collection": "Colección",
      }
    },
    "articles": {
      "menu": {
        "wool": "Lana y otros materiales",
        "labels": "Las etiquetas",
        "spitzberg": "Chaqueta de Spitsbergen",
      },
      "title": "Ropa: ",
      "lin": {
        "liste1": ", oveja y cordero provienen de la esquila de vellones. Según las razas serán más o menos amables. También preste atención a su origen, las ovejas pueden estar en Australia / América del Sur, la lana lavada y procesada en China y el hilado en Francia. Merino es muy suave y en Francia Arles merino, también está Ouessant, Shetland ... La estructura de la lana le da buena elasticidad, además tiene una memoria de forma que evita la deformación con el tiempo. Es resistente a las arrugas y fácil de teñir. Tiene muchas cualidades térmicas y permite que el cuerpo mantenga una temperatura constante, permite que la piel respire y permite que la transpiración escape.",
        "liste2": ", provienen de cabras. La cachemira proviene de las cabras del Himalaya, es la capa interna del vellón. Es muy fino, suave y con cualidades térmicas muy eficientes. Las cabras de angora proporcionan el mohair que encontramos clasificados en diferentes categorías de acuerdo con su finura, el más fino es el mohair para niños (de niños). Esta lana se hincha con aire tan pronto como hace frío, lo que le da cualidades térmicas excepcionales. Francia ofrece una amplia variedad de ellos gracias a nuestra cría artesanal. A menudo se encuentra asociado con la seda en forma de Kid-silk.",
        "liste21": ". El más extendido y también controvertido dado el daño ecológico causado, una gran cantidad de pesticidas y mucho consumo de agua. Elija los que tienen certificación GOTS. Es absorbente y aislante, y es muy resistente al lavado incluso a altas temperaturas. Es suave, pero puede ser pesado de usar y cálido.",
        "liste22": ": descuidado por mucho tiempo a favor del algodón, vemos que vuelve a la palestra por su cultivo que requiere poco fertilizante y agua. Es muy sólido, termorregulador, muy ligero. Su lado áspero se desvanece con el lavado.",
        "liste23": ", muy absorbente, rivaliza con el algodón, mucho más fácil de cultivar. Es suave y cómodo, y muy resistente, puede reemplazar el nylon en la fabricación de calcetines. Es resbaladizo y bastante pesado. Mire su origen, las condiciones de crecimiento no son las mismas en Europa que en Asia.",
        "liste24": ", una fibra de la que sé muy poco, aparentemente artificial porque se regenera a partir de las proteínas contenidas en las semillas, es lo que hace mucho trabajo de transformación. Es tan brillante como la seda, hipoalergénico, lavable y resistente a la luz y al sudor.",
        "liste25": ": fibra de la Edad Media que recupera sus letras de nobleza, por su cultivo rápido y productivo con poca agua, fertilizantes y pesticidas. Muy similar al lino, también es termorregulador, funciona bien tanto en verano como en invierno y se suaviza con el tiempo.",
        "liste26": " (o lyocell), se extrae de la pulpa de madera de eucalipto. Es una reminiscencia de la seda por su apariencia y su tacto. Es resistente a las arrugas y fácil de mantener, ya que se puede lavar a máquina a 60 ° C.",
        "liste3": ": es una fibra extremadamente suave y hasta 9 veces más cálida que la lana de oveja. Hay que prestar atención al origen y las condiciones de la cosecha , en Alemania se despojan los conejos, en Francia se peinan con un peine, en Asia se sacrifica el conejo. Por lo tanto, preste atención a sus proveedores y vaya a Caregora angora (respeto estricto por el bienestar animal, con certificación europea).",
        "liste4": ", muy suave, cálida, ligera y resistente, es una fibra de alta gama. La fibra de alpaca para bebés es ideal para pieles sensibles, especialmente para canastillas. Muchas crías se han desarrollado en Francia.",
        "liste5": ", tiene cualidades similares a la cachemira, suavidad al tacto y calor. Es una fibra bastante rara que solo se puede cosechar de manera artesanal en primavera deshierbando porque El animal pierde naturalmente su pelo. A menudo se encuentra tejido con seda o lana de cordero.",
        "liste6": ", tomado de la parte inferior del camello, es extremadamente raro. En virtud de sus cualidades, es muy similar a la lana de yak.",
        "liste7": ": es una fibra proteica resultante del capullo producido por la oruga del morera de la morera para el cultivo y de Tussah para la seda salvaje. Le da una brillante interpretación al Sus ventajas son su elasticidad natural, su solidez, su capacidad para absorber colorantes y su termorregulación, permite que la piel respire en verano y se caliente en invierno. A menudo se encuentra mezclada con otras fibras como el mohair.",
        "soustitre1": 'Las diferentes fibras animales:',
        "soustitre2": 'Las diferentes fibras vegetales naturales:',
        "strong1": "La lana de oveja",
        "strong2": "Angora y lana de cachemira",
        "strong21": "Algodón",
        "strong22": "Linen",
        "strong23": "Bamboo",
        "strong24": "Soja",
        "strong25": "Cáñamo",
        "strong26": "tencel",
        "strong3": "lana de conejo de angora",
        "strong4": "Lana de alpaca",
        "strong5": "lana de yak",
        "strong6": "Lana de camello",
        "strong7": "seda",
        "texte1": "Cc, conoces mis ideas sobre el tema también te daré la topografía sobre hilos sintéticos, encontrarás acrílico, nylon y poliamida, poliéster, lurex (una rara excepción que puedes encontrar en mis diseños). La ventaja de estos materiales es su facilidad de mantenimiento, su bajo costo. Sus inconvenientes son de baja calidad térmica (daños para un suéter), provienen de productos petroquímicos e incluso una vez producidos, continúan contaminando con cada lavado a través de aguas residuales, las micropartículas que emergen de ellos pasan a través de los filtros. plantas de tratamiento de aguas residuales para terminar en el mar.",
        "texte2": "Los hilos de tejer naturales están hechos de fibras animales o vegetales hiladas, comúnmente llamadas lana. La ventaja es su calidad térmica y transpirable, y que no tienen olor, solo necesita ventilar su suéter, no necesita lavarlo cada vez que lo usa, la desventaja es precisamente el lavado porque el Las lanas pueden sentirse bajo el efecto del cambio repentino de temperatura y los movimientos del tambor de la máquina. Los hilos de superlavado (SW) existen para evitar esto, pero este proceso utiliza muchos productos químicos y agua, por lo que tiene un fuerte impacto en el medio ambiente tanto como usted sabe. A diferencia de las fibras animales, las fibras vegetales no son muy elásticas.",
        "texte3": "Materiales que, a diferencia de las fibras animales, tienen la ventaja de ser generalmente lavados a máquina. Y veganos para vestirse naturalmente.",
        "texte4": "Gracias a los diversos blogs y wiki que me permitieron documentarme sobre el tema.",
        "titre1": 'Hilos, lanas y otros materiales ',
        "titre2": "¿Qué elegir?",
      },
      "labels": {
        "lien1": "Fuentes: Eco-sapiens, My Races for the Planet",
        "liste1": "Ecología - Protección del medio ambiente - Enfoque ético y sostenible - RSE",
        "liste2": "Social - Respeto por la condición humana",
        "liste21": "Metales pesados ​​en su conjunto, ",
        "liste22": "Alteradores endocrinos, ",
        "liste23": "Retardantes de llama bromados o clorados, ",
        "liste24": "Organismos modificados genéticamente u OMG, ",
        "liste25": "Nanotecnología, ",
        "liste26": "Sustancias cancerígenas, ",
        "liste27": "PVC, ",
        "liste28": "Níquel, ",
        "liste29": "El cromo, ",
        "liste3": "Comercio justo",
        "liste30": "Métodos de impresión que utilizan disolventes aromáticos, ",
        "liste31": "Métodos de impresión de plastisol utilizando ftalatos y PVC. ",
        "liste4": "Origen orgánico - Productos certificados sin pesticidas - Cuero ecológico - Productos veganos",
        "liste40": "Regar los cultivos de algodón que deben ser razonados, ",
        "liste41": "Aguas residuales que deben tratarse en una planta de tratamiento, ",
        "liste42": "Embalaje que debe ser reciclable. ",
        "liste5": "Salud",
        "soustitre1": "OEKO-TEX 100",
        "soustitre10": "NATURTEXTIL",
        "soustitre11": "NATURLEDER",
        "soustitre12": "ASOCIACIÓN DE SUELOS ORGÁNICOS",
        "soustitre13": "EMPRESA PATRIMONIO VIVO (EPV)",
        "soustitre14": "FUNDACIÓN DE DESGASTE JUSTO (FWF)",
        "soustitre15": "MADE IN RESPECT",
        "soustitre16": "ORGÁNICO",
        "soustitre2": "HECHO EN VERDE",
        "soustitre3": "MAX HAVELAAR",
        "soustitre4": "COMERCIO JUSTO ORGÁNICO",
        "soustitre5": "ECOCERT",
        "soustitre6": "BIORE",
        "soustitre7": "EUROPEAN ECOLABEL",
        "soustitre8": "ORIGEN FRANCIA GARANTIZADA",
        "soustitre9": "DEMETRO",
        "strong1": "Y lo que aprecio especialmente como cliente son las pruebas de desgaste, porque para ser lógico, la prenda debe poder durar con el tiempo, a fin de limitar su producción y su impacto ambiental. ",
        "strong10": "al menos 70% de fibras naturales o de materiales renovables o reciclados. ",
        "strong10bis": "política medioambiental",
        "strong11": "respetuoso con el medio ambiente y la salud del consumidor. ",
        "strong12": "convenciones internacionales",
        "strong13": "un papel de protección e información del consumidor",
        "strong14": "prohibir el uso de sustancias peligrosas",
        "strong15": "algodón producido a partir de agricultura ecológica. ",
        "strong16": "ausencia de productos químicos",
        "strong17": "tratamiento de aguas residuales antes de su liberación a la naturaleza. ",
        "strong18": "buenas condiciones laborales",
        "strong19": "trazabilidad del producto. ",
        "strong2": "textiles sin productos tóxicos para el cuerpo y el medio ambiente. ",
        "strong20": "el impacto ambiental de los productos a lo largo de su vida útil. ",
        "strong21": "enfoque global",
        "strong22": "toma en consideración el ciclo de vida del producto desde la extracción de materias primas, fabricación, distribución y uso hasta el reciclaje o eliminación después del uso. ",
        "strong23": "para garantizar la fabricación francesa en su totalidad o en parte. ",
        "strong24": "preservación del empleo y cumplimiento de las normas sociales, ambientales y de salud. ",
        "strong25": "que al menos el 50% del producto está hecho en Francia. ",
        "strong26": "de granjas certificadas Demeter",
        "strong27": "más exigente que el de la agricultura ecológica certificada con el logotipo AB. ",
        "strong28": "cosechado a mano, la mecanización sólo es posible cuando se excluye el uso de productos químicos. ",
        "strong29": "fibras naturales",
        "strong3": "Los textiles son seguros para la salud de los consumidores (sin productos químicos nocivos) y también se producen de manera sostenible y socialmente responsable. ",
        "strong30": "hasta un 50%. ",
        "strong31": "al menos el 95% de sus fibras proceden de la agricultura ecológica",
        "strong32": "Se prohíben sustancias como el cloro, metales pesados, níquel, así como cualquier producto que pueda contener OMG. ",
        "strong33": "Registro permanente de uso de sustancias químicas y energía, consumo de agua y tratamiento de aguas residuales. Los materiales de almacenamiento no deben contener PVC. ",
        "strong34": "también supervisa las condiciones laborales",
        "strong35": "ser cuero ecológico certificado. ",
        "strong36": "Las pieles se conservan en frío y con sal, sin agentes químicos. Está prohibido el curtido con cromo u otros productos contaminantes. Solo productos vegetales y aquellos con aluminio, circonio o titanio. ",
        "strong37": "animales criados principalmente para su carne. ",
        "strong38": "al menos el 70% de las fibras deben ser orgánicas y no contener sustancias nocivas. ",
        "strong39": "criterio social y respeta los convenios de la Organización Internacional del Trabajo (OIT). ",
        "strong4": "A partir de pruebas específicas y códigos QR, los procesos textiles y de fabricación se pueden detallar y rastrear. ",
        "strong40": "mantener su actividad productiva en Francia. ",
        "strong40bis": "Empresas francesas con excelentes conocimientos artesanales e industriales. ",
        "strong41": "El objetivo es contribuir a la mejora de las condiciones laborales en la industria textil. ",
        "strong42": "Prohibición del trabajo forzoso, no discriminación en el empleo, libertad de asociación, condiciones de trabajo decentes (higiene, salud), el trabajo infantil está prohibido, horarios y salarios controlados, toda discriminación prohibida. ",
        "strong43": "responsabilidad social y ambiental",
        "strong44": "a la calidad y el saber hacer, las condiciones sociales, el ecodiseño y el respeto al medio ambiente, así como a la ética económica. ",
        "strong45": "un nivel de algodón orgánico en el producto terminado pero no garantiza las etapas de transformación del textil y en particular el teñido. ",
        "strong46": "Así que es una etiqueta poco confiable, especialmente cuando se ve dónde producen estas marcas y las condiciones laborales que imponen a sus empleados (ver subcontratistas). ",
        "strong5": "el producto cumple con los criterios internacionales de comercio justo relacionados con las condiciones de producción y la remuneración del productor. Garantiza el cumplimiento de los convenios de la Organización Internacional del Trabajo (OIT). ",
        "strong6": "criterios ambientales: los OMG están prohibidos, pero no los pesticidas. ",
        "strong7": "producción orgánica",
        "strong8": "una carta justa y humana",
        "strong9": "en defensa de los consumidores, el medio ambiente y los trabajadores",
        "texte1": "¿Por qué le interesan las etiquetas textiles?",
        "texte10": "Por lo que es inevitable, la etiqueta ecológica hace concesiones sin, sin embargo, cumplir con la ley del mercado. Por así decirlo, la certificación GOTS busca limitar su uso con medidas como:",
        "texte11": "En lo que respecta a asuntos sociales, no hace falta decir (-pero ciertamente no tanto, ya que hay que decirlo, nuevamente todo depende del país de origen ^^) que el trabajo forzado, los niños y se prohíbe la discriminación, además de las recomendaciones de la OIT (organización internacional del trabajo), a saber, horarios y salarios dignos, el derecho de sindicación y las condiciones de higiene y seguridad ",
        "texte12": "Esta es una de las etiquetas más comunes, de origen alemán. Es la primera etiqueta que garantiza",
        "texte13": "Es una etiqueta confiable pero también puede certificar materiales sintéticos y por lo tanto contaminantes aguas arriba",
        "texte14": "Lo encontramos en diferentes formas",
        "texte15": "La etiqueta estándar ÖKO-TEX 100 ayuda a proteger al consumidor. De hecho, los productos etiquetados no contienen productos químicos que puedan ser tóxicos para los consumidores, como formaldehídos o metales pesados, por ejemplo. Esta etiqueta internacional es ampliamente utilizado especialmente para ropa de cama para niños pequeños. ",
        "texte16": "También existe la etiqueta ÖKO-TEX standard 1000 que certifica que la producción respeta el medio ambiente durante todas sus etapas. ",
        "texte17": "Finalmente, el estándar ÖKO-TEX 100 plus certifica que los productos etiquetados están libres de sustancias tóxicas y provienen de una producción ecológica. ",
        "texte18": "Estas otras dos formas de la etiqueta textil estándar internacional ÖKO-TEX no están muy extendidas y son bastante raras de encontrar en los textiles. ",
        "texte19": "Oeko-Tex también ha creado una nueva certificación Made in Green. Es la garantía de que",
        "texte2": "En un enfoque ecológico y sostenible por supuesto. Aunque signifique tanto hacer la artesanía como hacerlo bien y sobre todo elegir sus materias primas con toda conciencia. La industria textil utiliza una cuarta parte de los productos químicos del mundo y ha sido acusada 20% de la contaminación del agua por industria, lo que la convierte en el segundo mayor contaminador de agua dulce del planeta, razón por la cual, además de los estándares y regulaciones, las etiquetas un papel que jugar, en términos de apoyo a las marcas, y también como garantía de calidad para el consumidor final. Gracias a todos los que ya han escrito sobre el tema, blogs y otros donde me he documentado para ofrecerles la más amplia gama de posibilidades. ",
        "texte20": "Gracias al uso de un número",
        "texte21": "Made in Green reemplaza el antiguo sistema de certificación, Oeko-Tex Standard 100 Plus y la etiqueta española Made in Green de Aitex. ",
        "texte22": "Esta es la etiqueta de comercio justo. Garantiza que el",
        "texte23": "Es una buena etiqueta, pero es menos exigente",
        "texte24": "Esta etiqueta garantiza un",
        "texte25": "materia prima, especialmente algodón. También se aplica",
        "texte26": "que reconcilia la ecología y lo social. En una lógica global, la etiqueta involucra a todos los actores de la cadena. ",
        "texte27": "Es una etiqueta que funciona",
        "texte28": ". Por lo tanto, tiene varios objetivos. ",
        "texte29": "Lo primero es proteger el planeta y sus recursos mediante el uso de",
        "texte3": "Cada etiqueta verifica y prioriza uno o más aspectos de la cadena de valor. Desde la producción de telas hasta el producto terminado. Estos son algunos ejemplos de áreas en las que se especializan las etiquetas:",
        "texte30": "Pero también definiendo una <strong> política medioambiental ",
        "texte30bis": "exigir una reducción del consumo de agua y energía, mediante el uso de tintes, agentes textiles y procesos de fabricación",
        "texte31": "También actúa garantizando lo principal",
        "texte32": "en materia social, salud y seguridad en el trabajo. ",
        "texte33": "Finalmente, él tiene",
        "texte34": "proporcionando información clara sobre la naturaleza de las fibras que componen el producto y por",
        "texte35": "(por ejemplo, metales pesados, aminas cancerígenas, formaldehídos, enzimas transgénicas, etc.). ",
        "texte36": "Pero sigue siendo muy inferior a los requisitos de GOTS",
        "texte37": "Es una etiqueta suiza que tiene garantías ecológicas, éticas y sociales. Certifica la materia prima de",
        "texte38": "A nivel ambiental, certifica el",
        "texte4": "Siendo la industria textil una de las más contaminantes del mundo, la industria de las etiquetas iba a empezar pronto. Siempre más verde que verde ... ¿Pero qué hacemos? vender ??? Y sí, comprar telas etiquetadas o lanas / hilos tiene un costo que el consumidor final tendrá que pagar. Así que es mejor que los conozca para elegir el correcto. ",
        "texte40": "También tiene un rol social al garantizar",
        "texte41": "(no trabajo infantil, seguridad laboral, salario mínimo…). ",
        "texte42": "También asegura",
        "texte43": "Incluso podemos averiguar quién hizo la prenda visitando el sitio web de la marca. ",
        "texte44": "Esta etiqueta europea evalúa",
        "texte45": "Se basa en el principio de",
        "texte46": "quién",
        "texte47": "Esta etiqueta se refiere solo al medio ambiente y no ofrece ninguna garantía social. ",
        "texte48": "Esta es la etiqueta oficial para",
        "texte49": "Esta es una garantía contra la falsificación hecha en Francia y, por lo tanto, para el",
        "texte5": "Gracias a todos los que escribieron sobre el tema y me permitieron documentarme ... La wiki es tu mejor amiga ...",
        "texte50": "Él certifica",
        "texte51": "La otra mitad del producto se puede hacer en otro lugar ... Lamentamos que esta etiqueta no se aplique al 100%. ",
        "texte52": "La etiqueta Demeter es muy exigente. Implica que la materia prima del textil (lana, algodón o fibras de lino) es",
        "texte53": ", según las especificaciones",
        "texte54": "El algodón debe ser",
        "texte55": "Las fibras animales deben cortarse o peinarse. ",
        "texte56": "La etiqueta textil Demeter puede otorgarse a productos que contengan",
        "texte57": "convencional que no estaría disponible bajo la etiqueta Demeter",
        "texte58": "Esta etiqueta cumple con especificaciones estrictas y rigurosas. ",
        "texte59": "Los textiles etiquetados tienen",
        "texte6": "Por lo tanto, haré una pequeña lista para ti detallando las dos principales, ya que si tengo que confiar en una etiqueta, será una de estas dos ... Después para lana, certificada o no, prefiero Siempre un pequeño criador francés, o filiación, al menos no estamos seguros de favorecer la cría francesa y no evitamos el costo del carbono (especialmente porque algunas etiquetas como AB, no tienen nada que ver con la AB francesa). .. De todos modos, ¡¡¡de vuelta al tema !!!! ",
        "texte60": "o en conversión. En cada etapa del proceso de producción, se debe verificar que las fibras orgánicas y convencionales no estén mezcladas, y que las fibras orgánicas no estén contaminadas de ninguna manera. ",
        "texte61": "El proceso de fabricación de prendas de vestir también está muy controlado. ",
        "texte62": "Desde un punto de vista medioambiental, los socios están sujetos a un estatuto muy estricto de",
        "texte63": "Finalmente, la etiqueta",
        "texte64": ": respeto por los derechos de los empleados, prohibición del trabajo forzoso (así como el hecho de exigir a los trabajadores que dejen sus documentos de identidad con su empleador), lugar de trabajo seguro y saludable, el trabajo infantil está prohibido , no se autoriza ninguna discriminación de ningún tipo (falta de promoción, diferencia de remuneración, etc.),… ",
        "texte65": "Esta es la primera etiqueta",
        "texte66": "Limita en gran medida los impactos de una industria muy contaminante. Garantiza un",
        "texte67": "Los tintes que contienen metales pesados ​​también están prohibidos. ",
        "texte68": "Esta etiqueta también garantiza que las máscaras deben pertenecer a",
        "texte69": "Finalmente, esta etiqueta tiene los mismos criterios sociales que la etiqueta textil descrita anteriormente. ",
        "texte7": "GOTS para",
        "texte70": "Esta es la etiqueta orgánica más grande del Reino Unido. Certifica productos orgánicos y campañas para una agricultura respetuosa con el medio ambiente y una producción de alimentos más segura y saludable. ",
        "texte71": "Concerniente a los textiles, ",
        "texte72": "Esta etiqueta también tiene en cuenta",
        "texte73": "La etiqueta Entreprise du Patrimoine Vivant (EPV) es una etiqueta francesa. Es una marca de reconocimiento del Estado que distingue ",
        "texte73bis": "En particular, distingue los conocimientos tradicionales de calidad (como el encaje). Les Entreprises du Patrimoine Vivant",
        "texte74": "Fair Wear Foundation es una fundación que trabaja para respetar las condiciones laborales dignas en las empresas. Su",
        "texte75": "Para ello, ha creado un Código de Prácticas Laborales que las marcas se comprometen a respetar. Los principios fundamentales de este código son los siguientes:",
        "texte76": "La FWF se compromete entonces a verificar la aplicación de estos principios en las fábricas de hilados y textiles. ",
        "texte77": "El objetivo de esta etiqueta es brindar a las pequeñas empresas, en particular las industriales, una herramienta para promover sus enfoques éticos",
        "texte78": "(RSE), fácil de configurar, económico y confiable. ",
        "texte79": "Los criterios combinan aspectos relacionados",
        "texte8": "es para mí la referencia en la materia. Es una etiqueta que se encuentra más bien en Reino Unido, Estados Unidos y Japón (me encantan sus tejidos). Desde 2008 pretende armonizar los estándares del sector textil en todo el mundo y me interesa sobre todo porque tiene las especificaciones más estrictas para lana, algodón, seda, cáñamo (falta el lino ... pero bueno). independiente para controlar la aplicación de las especificaciones que el productor se ha comprometido a respetar. ",
        "texte80": "Estos principios, por tanto, tienen como objetivo promover productos fabricados de una manera verdaderamente sostenible. ",
        "texte81": "Es una organización estadounidense que tiene como objetivo promover el uso del algodón orgánico y que cuenta con el apoyo de marcas como Nike, Walmart, H&M, Adidas, Patagonia, Marks & Spencer ... Se trata de tener un estándar que permita para acceder fácilmente al algodón orgánico. ",
        "texte82": "Esta certificación garantiza",
        "texte83": "No incluye elementos referentes a las condiciones sociales de producción. ",
        "texte9": "Cada producción tiene su propio cuaderno, por supuesto; pero en general encontramos lo que está prohibido:",
        "title": "LAS ETIQUETAS",
      },
      "spitz": {
        "title": "Chaqueta Spitsbergen",
        "texte1": "Les presento la chaqueta Spitsbergen.",
        "texte2": "Necesitarás una talla 40/42:",
        "texte3": "13 bolas de Barisienne 12 (Bergère de France): -6 ming, 2 cuervo, 2 zinzolin, 2 cenit, 1 armadura",
        "texte4": "Aig n ° 12",
        "texte5": "Circular Aig n ° 8",
        "texte6": "Gancho n ° 8 para las costuras",
        "texte7": "Aig auxiliar",
        "texte8": "Puntos utilizados:",
        "texte9": "punto de musgo:",
        "texte10": "Número de malla múltiplo de 4",
        "texte11": "1a y 2a hileras: * 1m final 1m.env * repetir. desde * hasta *",
        "texte12": "3ra y 4ta fila: * 1m.env.1m.final. * Repetir. De * a *",
        "texte13": "Giro con cable:",
        "texte14": "en 10 puntos",
        "texte15": "1ª y 3ª fila. (aprox. de apertura) 2m final., 6m final.",
        "texte16": "2a fila: 2m.env.6mend.2m.env.",
        "texte17": "4a fila: aprox.2 m, deslizamiento 3 m. En la aguja. Al. Colocado detrás (o delante), 3 m. Termina y luego trabaja. Al final. Los 3m. Desde el aig. Al. ; 2 m Aprox.",
        "texte18": "5 y 7rgs. : como 1ª y 6ª fila.",
        "texte19": "6o como 2do",
        "texte20": "Octavo como cuarto",
        "texte21": "Reanudar rango1",
        "texte22": "será pesado pero te aconsejo que hagas ambos lados al mismo tiempo",
        "texte23": "subir 28m. en azul y 28m. en parma",
        "texte24": "1m. borde 8m. en punto musgo, 10m. para el giro con cable (lado azul afilado detrás de la abertura y lado violeta afilado. dvt.), 8 m. en punto musgo, 1m. borde",
        "texte25": "10ª fila: dim. De un pt. a la derecha para el lado azul y a la izquierda. para el lado morado",
        "texte26": "desde el 13º rg. y hasta el 26 rg. reemplace el cable con punto jersey (ubicación del bolsillo)",
        "texte27": "20a fila: tenue.",
        "texte28": "30ª fila: dim. De un pt. a la derecha / g.",
        "texte29": "Fila 40: agosto de una m. a la derecha / g.",
        "texte30": "60a fila: agosto de una m. a la derecha / g.",
        "texte31": "Fila 66 rematar 3m a derecha / izquierda. (lado de la sisa)",
        "texte32": "Hilera 67 rematar 3 puntos derecho / izquierdo (lado de la sisa)",
        "texte33": "Hilera 68 rematar 1 pt / hilera (lado de la sisa)",
        "texte34": "69a hilera rematar 1 pt / hilera (lado de la sisa)",
        "texte35": "Hilera 70 rematar 1 pt / hilera (lado de la sisa)",
        "texte36": "Hilera 71 rematar 1 punto a la derecha / izquierda (lado de la sisa)",
        "texte37": "74,76,78, 80, 82,84, 88,90ª fila rematar 1m.",
        "texte38": "92ª fila rematar 15 m. Restante",
        "texte39": "subir 16m. centrando el giro con cable en 16rg.",
        "texte40": "Rematar y tejer en su lugar",
        "texte41": "crochet los lados en la espalda",
        "texte42": "en 24 puntos",
        "texte43": "nota: CG: cruzado a la izquierda, 3 pts en la ag en la abertura, 3 d., derecho. M se deslizó hacia K.",
        "texte44": "CD: cruce a la derecha, 3 m en aig .aux. detrás.abierto. , K 3, tejer m deslizado a K",
        "texte45": "SCG: cruce simple a la izquierda: 3 m en aig.aux.dvt.l'ouv.1m.env.3m.",
        "texte46": "SCD: simple cruce a la derecha. : deslice 1m. En la ag detrás de la abertura, 3 pts, deslizar aprox 1 pt hilera. (aprox. de la apertura) 2m final., 3m .pp., 4m. final., 6m.",
        "texte47": "2a fila: aproximadamente 2 m, aproximadamente 3 m, aproximadamente 4 m, CD, aproximadamente 4 m, aproximadamente 3 m, aproximadamente 2 m.",
        "texte48": "3ª fila: y todas las filas. impar. Tric. las m. como se presentan.",
        "texte49": "4ª fila: aprox.2 m, (SCG, aprox. 2 m, SCD) X2, aprox. 2 m.",
        "texte50": "6ª fila: aprox.3 m, SCG, SCD, aprox.2 m, SCG, SCD, aprox.3 m.",
        "texte51": "8a fila: aprox.4 m, CG, aprox.4 m, CD, aprox.4 m.",
        "texte52": "Décima fila: aprox.3 m, SCD, SCG, aprox.2 m, SCD, SCG, aprox.3 m.",
        "texte53": "12a fila: aprox.2 m, (SCD, aprox. 2 m, SCG) X2, aprox. 2 m.",
        "texte54": "14a hilera: 2m.env., 3m.fin., 4m.env., CG, 4m.env., 3m.end., 2m.env.",
        "texte55": "16a fila: cm. fila 4",
        "texte56": "18a fila: cm. fila 6",
        "texte57": "20ª fila: aprox.4 m, CD, aprox.4 m, CG, aprox.4 m.",
        "texte58": "22a fila: cm. fila 10",
        "texte59": "24a fila: cm. fila 12",
        "texte60": "Reanudar fila 1",
        "texte61": "monter 52m. En rouge ",
        "texte62": "O 1 m. borde 13m. en punto musgo, 24m. Para los giros superpuestos, 13m. en punto musgo, 1m. borde",
        "texte63": "10ª fila: dim. De un pt. al cap. fin",
        "texte64": "20ª fila: dim. De un pt. al cap. fin",
        "texte65": "30ª fila: dim. De un pt. al cap. fin",
        "texte66": "Fila 40: agosto de una m. al cap. fin",
        "texte67": "60a fila: agosto de una m. al cap. fin",
        "texte68": "Fila 66 rematar 3m.",
        "texte69": "67ª fila rematar 3 m.",
        "texte70": "68a fila rematar 1m.",
        "texte71": "69ª fila rematar 1m.",
        "texte72": "70ª fila rematar 1m.",
        "texte73": "71ª fila rematar 1m.",
        "texte74": "Fila 90 rematar 10 m.",
        "texte75": "91ª fila rematar 10 m.",
        "texte76": "92ª fila rematar 20 m. Restante",
        "texte77": "Mon 26 pts (8 pts en pt arroz, 10 para el giro con cordón, 8 pts en pt arroz)",
        "texte78": "En cuanto a la parte delantera, haz ambas mangas al mismo tiempo",
        "texte79": "manga derecha: aguda. al. detrás de la abertura. rojo (32 filas), azul (18 filas), negro (5 filas antes de dim. + 12 filas),",
        "texte80": "manga izquierda: aguda. al. frente a la op. rojo (32 filas), morado (18 filas), negro (5 filas antes de atenuar + 12 filas),",
        "texte81": "Ago. una puntada en cada extremo de la 3ª fila y cada tercera fila para llegar a la 39ª fila a 52 m.",
        "texte82": "En la 46ª fila, rem 3 pts.",
        "texte83": "En la 47ª hilera rem 3 pts.",
        "texte84": "En la vta 48 rem 2 pts.",
        "texte85": "En la 49ª fila, rem 2 pts.",
        "texte86": "En la hilera 50 rem 1 pt.",
        "texte87": "En la fila 51 rematar 1m ..... Hasta la fila 58",
        "texte88": "rematar los 37m. restante",
        "texte89": "coser la manga en las filas 55. luego coser al cuerpo",
        "texte90": "subir 7m. en negro",
        "texte91": "tejer la 12ª fila. en punto de musgo",
        "texte92": "hacer 2 filas en morado, 2 filas en rojo, 2 filas en azul, reanudar en negro sobre 120 cm, detener",
        "texte93": "hacer un lazo en un lado del cuerpo para fijar el cinturón, coserlo en el gancho",
        "texte94": "bola gris, usando el gancho, montar en la aguja. circular 188m. que tejerás en 1/1 de probabilidades sobre 5rg. Cerrar los 110 pts. en gris y los 78 restantes en negro",
        "subTitle1": "Anverso:",
        "subTitle2": "Bolsillos en rojo:",
        "subTitle3": "Dos:",
        "subTitle4": "Giros superpuestos:",
        "subTitle5": "Mangas:",
        "subTitle6": "Cinturón:",
        "subTitle7": "Escote:",
      }
    },
    "navbar": {
      "home": "Bienvenida",
      "shop": "Tienda",
      "articles": "Artículos",
      "lang": "lengua",
      "connection": "Conexión",
      "cart": "Cesta",
    }
  }
}

export default es;