export default {
  products: [
    {
      _id: 1,
      name: 'Slim shirt',
      category: 'Shirts',
      image: '/images/d1.jpg',
      price: 60,
      brand: 'Nike',
      rating: 4.5,
      reviews: 10,
      countInStock: 3,
    },
    {
      _id: 2,
      name: 'Slim shirt',
      category: 'Shirts',
      image: '/images/d1.jpg',
      price: 60,
      brand: 'Nike',
      rating: 4.5,
      reviews: 10,
      countInStock: 4,
    },
    {
      _id: 3,
      name: 'Fit shirt',
      category: 'Shirts',
      image: '/images/d1.jpg',
      price: 60,
      brand: 'Nike',
      rating: 4.5,
      reviews: 10,
      countInStock: 5,
    },
    {
      _id: 4,
      name: 'Slim shirt',
      category: 'Shirts',
      image: '/images/d1.jpg',
      price: 60,
      brand: 'Nike',
      rating: 4.5,
      reviews: 10,
      countInStock: 6,
    },
    {
      _id: 5,
      name: 'Best pants',
      category: 'Pants',
      image: '/images/d1.jpg',
      price: 60,
      brand: 'Nike',
      rating: 4.5,
      reviews: 10,
      countInStock: 7,
    },
    {
      _id: 6,
      name: 'Slim shirt',
      category: 'Pants',
      image: '/images/d1.jpg',
      price: 60,
      brand: 'Nike',
      rating: 4.5,
      reviews: 10,
      countInStock: 8,
    },
  ]
}